In [1]:
import numpy as np
import numpy.matlib 
import random



In [2]:
#order：k*l*m 100*100*25

In [3]:
G = np.zeros((31,31,15))
for k in range (0,31):
    for l in range (0,31):
        for m in range(0,15):
            if k==0 and l==0 and m==0:
                continue
            else:
                G[k,l,m] = (2*m*m-k*k-l*l)/((k*k+l*l+m*m)**(5/2))
print(G)            

[[[ 0.00000000e+00  2.00000000e+00  2.50000000e-01 ...  1.15740741e-03
    9.10332271e-04  7.28862974e-04]
  [-1.00000000e+00  1.76776695e-01  1.25219807e-01 ...  1.13360536e-03
    8.94350177e-04  7.17812789e-04]
  [-1.25000000e-01 -3.57770876e-02  2.20970869e-02 ...  1.06577137e-03
    8.48459680e-04  6.85893578e-04]
  ...
  [-4.55539359e-05 -4.52931589e-05 -4.45190797e-05 ... -1.89065260e-05
   -1.59075247e-05 -1.30382972e-05]
  [-4.10020911e-05 -4.07832407e-05 -4.01331482e-05 ... -1.81607824e-05
   -1.55154562e-05 -1.29658039e-05]
  [-3.70370370e-05 -3.68522797e-05 -3.63031055e-05 ... -1.73780153e-05
   -1.50415313e-05 -1.27743063e-05]]

 [[-1.00000000e+00  1.76776695e-01  1.25219807e-01 ...  1.13360536e-03
    8.94350177e-04  7.17812789e-04]
  [-3.53553391e-01  0.00000000e+00  6.80413817e-02 ...  1.11041135e-03
    8.78716945e-04  7.06971052e-04]
  [-8.94427191e-02 -3.40206909e-02  1.23456790e-02 ...  1.04428915e-03
    8.33817705e-04  6.75648507e-04]
  ...
  [-4.54669179e-05 -4.5

In [4]:
p = np.matlib.zeros((30*30*15,1))
Eex = np.matlib.zeros((30*30*15,1))

alpha1 = 1
alpha2 = 1

for i in range (0, 30*30*15):
    if i < 30*30*10 :
        Eex[i] = 5*alpha1
    else:
        Eex[i] = 5*np.exp(0.1*(-int(i/900)+9))*alpha2

In [5]:
print(Eex[900*10])

[[4.52418709]]


In [6]:
S = np.zeros((30,30))
for i in range (0,30):
    for j in range(0,30):
        S[i,j] = 10
for i in range(0,1000):
    x = random.randint(0,29)
    y = random.randint(0,29)
    if S[x,y] < 15:
        S[x,y] = S[x,y]+1
#print(S)

In [ ]:
M = np.matlib.zeros((30*30*15,30*30*15))

for i in range(0,30*30*15):
    if i%1000 == 0:
        print(i)
        
        #print(M[i,j])
    for j in range(0,30*30*15):
        l1 = (i%900)%30
        k1 = int((i%900)/30)
        m1 = int(i/900)
        
        l2 = (j%900)%30
        k2 = int((j%900)/30)
        m2 = int(j/900)
        
        if i == j:
            M[i,j] = 1.00000
        else :
            M[i,j] = alpha1*G[abs(l1-l2),abs(k1-k2),abs(m1-m2)]
        

0
100


In [20]:
p = np.linalg.solve(M,Eex)


In [19]:
print(M)

[[ 1.00000000e+00 -1.00000000e+00 -1.25000000e-01 ... -8.98811338e-06
  -8.71341125e-06 -8.44016118e-06]
 [-1.00000000e+00  1.00000000e+00 -1.00000000e+00 ... -9.26315892e-06
  -8.98811338e-06 -8.71341125e-06]
 [-1.25000000e-01 -1.00000000e+00  1.00000000e+00 ... -9.53732831e-06
  -9.26315892e-06 -8.98811338e-06]
 ...
 [-8.98811338e-06 -9.26315892e-06 -9.53732831e-06 ...  1.00000000e+00
  -1.00000000e+00 -1.25000000e-01]
 [-8.71341125e-06 -8.98811338e-06 -9.26315892e-06 ... -1.00000000e+00
   1.00000000e+00 -1.00000000e+00]
 [-8.44016118e-06 -8.71341125e-06 -8.98811338e-06 ... -1.25000000e-01
  -1.00000000e+00  1.00000000e+00]]


In [32]:
Polarizations = np.zeros(30*30*15)
for i in range(30*30*15):
    Polarizations[i] = p[i]

Polarizations = Polarizations.reshape((15,30,30))

In [33]:
print(Polarizations)

[[[ 0.48825213  0.58649316  0.92798392 ...  0.92798392  0.58649316
    0.48825213]
  [ 0.58649316  1.14733675  1.96015009 ...  1.96015009  1.14733675
    0.58649316]
  [ 0.92798392  1.96015009  3.11348075 ...  3.11348075  1.96015009
    0.92798392]
  ...
  [ 0.92798392  1.96015009  3.11348075 ...  3.11348075  1.96015009
    0.92798392]
  [ 0.58649316  1.14733675  1.96015009 ...  1.96015009  1.14733675
    0.58649316]
  [ 0.48825213  0.58649316  0.92798392 ...  0.92798392  0.58649316
    0.48825213]]

 [[ 1.40675083  1.62042765  1.88894545 ...  1.88894545  1.62042765
    1.40675083]
  [ 1.62042765  2.04862366  2.72488988 ...  2.72488988  2.04862366
    1.62042765]
  [ 1.88894545  2.72488988  3.91928482 ...  3.91928482  2.72488988
    1.88894545]
  ...
  [ 1.88894545  2.72488988  3.91928482 ...  3.91928482  2.72488988
    1.88894545]
  [ 1.62042765  2.04862366  2.72488988 ...  2.72488988  2.04862366
    1.62042765]
  [ 1.40675083  1.62042765  1.88894545 ...  1.88894545  1.62042765
    1.

In [46]:

np.save(file="Polarizations.npy", arr=Polarizations)

In [20]:
N[1,2] = -0.000033456

In [42]:
x = np.arange(12)
y = x.reshape(1,4,3)
print(y)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]]


In [17]:
i = 2356
j =2346

l1 = (i%900)%30
k1 = int((i%900)/30)
m1 = int(i/900)
        
l2 = (j%900)%30
k2 = int((j%900)/30)
m2 = int(j/900)

print(l1,l2,k1,k2,m1,m2)

16 6 18 18 2 2


In [ ]:
doc = open('Polarizations','w')
for i in range(30*30*15):
    print(p[i],file = doc)